version: '2'

volumes:
    
    app-data:
        driver: local

services:

    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/var/www/app
        working_dir: /var/www/app
        command: npm start
        links:
            - mongodb
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - app-data:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null
